<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-09T10:16:10Z" name="Default suite" finished-at="2022-03-09T10:16:23Z" duration-ms="13101">
    <groups>
    </groups>
    <test started-at="2022-03-09T10:16:10Z" name="Default test" finished-at="2022-03-09T10:16:23Z" duration-ms="13101">
      <class name="basic.automation.topic.to.learn.DragDropTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:basic.automation.topic.to.learn.DragDropTest@5bd03f44]" started-at="2022-03-09T15:46:10Z" name="openBrowser" finished-at="2022-03-09T15:46:16Z" duration-ms="6341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="dragDropTest()[pri:0, instance:basic.automation.topic.to.learn.DragDropTest@5bd03f44]" started-at="2022-03-09T15:46:16Z" name="dragDropTest" finished-at="2022-03-09T15:46:22Z" duration-ms="6034" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Drop here] but found [Dropped]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Drop here] but found [Dropped]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at basic.automation.topic.to.learn.DragDropTest.dragDropTest(DragDropTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragDropTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:basic.automation.topic.to.learn.DragDropTest@5bd03f44]" started-at="2022-03-09T15:46:22Z" name="closeBrowser" finished-at="2022-03-09T15:46:23Z" duration-ms="719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- basic.automation.topic.to.learn.DragDropTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
